class CfgPatches
{
	class ADDON
	{
		name = SPOKE;
        author = AUTHOR;
        requiredVersion = REQUIRED_VERSION;
		units[]={};
		weapons[]={};
		requiredAddons[]=
		{
			"A3_Weapons_F",
			"A3_Weapons_F_beta",
			"BFSQN_private_core"
		};
	};
};
class CfgAmmo
{
	class Default;
	class GrenadeCore;
	class ShotDeployBase;
	class GrenadeHand: GrenadeCore
	{
		access=3;
		airFriction=-0.00050000002;
		airLock=0;
		allowAgainstInfantry=1;
		animated=0;
		artilleryCharge=1;
		artilleryDispersion=1;
		artilleryLock=0;
		audibleFire=0.050000001;
		autoSeekTarget=0;
		caliber=1;
		cartridge="";
		cmImmunity=1;
		cost=40;
		CraterEffects="GrenadeCrater";
		craterShape="";
		CraterWaterEffects="ImpactEffectsWaterExplosion";
		deflecting=15;
		deflectionSlowDown=0.80000001;
		directionalExplosion=0;
		effectFlare="FlareShell";
		effectFly="";
		effectsFire="CannonFire";
		effectsMissile="ExplosionEffects";
		effectsMissileInit="";
		effectsSmoke="SmokeShellWhite";
		explosionAngle=60;
		explosionDir="explosionDir";
		explosionEffects="GrenadeExplosion";
		explosionEffectsDir="explosionDir";
		explosionEffectsRadius=5;
		explosionForceCoef="1.0f";
		explosionPos="explosionPos";
		explosionSoundEffect="DefaultExplosion";
		explosionTime=3.8;
		explosionType="explosive";
		explosive=1;
		fuseDistance=0;
		grenadeBurningSound[]={};
		grenadeFireSound[]={};
		hit=10;
		hitArmor[]=
		{
			"soundHit",
			1
		};
		hitBuilding[]=
		{
			"soundHit",
			1
		};
		hitConcrete[]=
		{
			"soundHit",
			1
		};
		hitDefault[]=
		{
			"soundHit",
			1
		};
		hitFoliage[]=
		{
			"soundHit",
			1
		};
		hitGlass[]=
		{
			"soundHit",
			1
		};
		hitGlassArmored[]=
		{
			"soundHit",
			1
		};
		hitGroundHard[]=
		{
			"soundHit",
			1
		};
		hitGroundSoft[]=
		{
			"soundHit",
			1
		};
		hitIron[]=
		{
			"soundHit",
			1
		};
		hitMan[]=
		{
			"soundHit",
			1
		};
		hitMetal[]=
		{
			"soundHit",
			1
		};
		hitMetalplate[]=
		{
			"soundHit",
			1
		};
		hitOnWater=0;
		hitPlastic[]=
		{
			"soundHit",
			1
		};
		hitRubber[]=
		{
			"soundHit",
			1
		};
		hitWater[]=
		{
			"soundHit",
			1
		};
		hitWood[]=
		{
			"soundHit",
			1
		};
		icon="";
		impactArmor[]=
		{
			"soundImpactIron1",
			0.2,
			"soundImpactIron2",
			0.2,
			"soundImpactIron3",
			0.2,
			"soundImpactIron4",
			0.2,
			"soundImpactIron5",
			0.2
		};
		impactBuilding[]=
		{
			"soundImpactHard1",
			0.2,
			"soundImpactHard2",
			0.2,
			"soundImpactHard3",
			0.2,
			"soundImpactHard4",
			0.1,
			"soundImpactHard5",
			0.1,
			"soundImpactHard6",
			0.1,
			"soundImpactHard7",
			0.1
		};
		impactConcrete[]=
		{
			"soundImpactHard1",
			0.2,
			"soundImpactHard2",
			0.2,
			"soundImpactHard3",
			0.2,
			"soundImpactHard4",
			0.1,
			"soundImpactHard5",
			0.1,
			"soundImpactHard6",
			0.1,
			"soundImpactHard7",
			0.1
		};
		impactDefault[]=
		{
			"soundImpactHard1",
			0.2,
			"soundImpactHard2",
			0.2,
			"soundImpactHard3",
			0.2,
			"soundImpactHard4",
			0.1,
			"soundImpactHard5",
			0.1,
			"soundImpactHard6",
			0.1,
			"soundImpactHard7",
			0.1
		};
		impactFoliage[]=
		{
			"soundImpactSoft1",
			0.2,
			"soundImpactSoft2",
			0.2,
			"soundImpactSoft3",
			0.2,
			"soundImpactSoft4",
			0.1,
			"soundImpactSoft5",
			0.1,
			"soundImpactSoft6",
			0.1,
			"soundImpactSoft7",
			0.1
		};
		impactGlass[]=
		{
			"soundImpactHard1",
			0.2,
			"soundImpactHard2",
			0.2,
			"soundImpactHard3",
			0.2,
			"soundImpactHard4",
			0.1,
			"soundImpactHard5",
			0.1,
			"soundImpactHard6",
			0.1,
			"soundImpactHard7",
			0.1
		};
		impactGlassArmored[]=
		{
			"soundImpactHard1",
			0.2,
			"soundImpactHard2",
			0.2,
			"soundImpactHard3",
			0.2,
			"soundImpactHard4",
			0.1,
			"soundImpactHard5",
			0.1,
			"soundImpactHard6",
			0.1,
			"soundImpactHard7",
			0.1
		};
		impactGroundHard[]=
		{
			"soundImpactHard1",
			0.2,
			"soundImpactHard2",
			0.2,
			"soundImpactHard3",
			0.2,
			"soundImpactHard4",
			0.1,
			"soundImpactHard5",
			0.1,
			"soundImpactHard6",
			0.1,
			"soundImpactHard7",
			0.1
		};
		impactGroundSoft[]=
		{
			"soundImpactSoft1",
			0.2,
			"soundImpactSoft2",
			0.2,
			"soundImpactSoft3",
			0.2,
			"soundImpactSoft4",
			0.1,
			"soundImpactSoft5",
			0.1,
			"soundImpactSoft6",
			0.1,
			"soundImpactSoft7",
			0.1
		};
		impactIron[]=
		{
			"soundImpactIron1",
			0.2,
			"soundImpactIron2",
			0.2,
			"soundImpactIron3",
			0.2,
			"soundImpactIron4",
			0.2,
			"soundImpactIron5",
			0.2
		};
		impactMan[]=
		{
			"soundImpact",
			1
		};
		impactMetal[]=
		{
			"soundImpactIron1",
			0.2,
			"soundImpactIron2",
			0.2,
			"soundImpactIron3",
			0.2,
			"soundImpactIron4",
			0.2,
			"soundImpactIron5",
			0.2
		};
		impactMetalplate[]=
		{
			"soundImpactIron1",
			0.2,
			"soundImpactIron2",
			0.2,
			"soundImpactIron3",
			0.2,
			"soundImpactIron4",
			0.2,
			"soundImpactIron5",
			0.2
		};
		impactPlastic[]=
		{
			"soundImpactSoft1",
			0.2,
			"soundImpactSoft2",
			0.2,
			"soundImpactSoft3",
			0.2,
			"soundImpactSoft4",
			0.1,
			"soundImpactSoft5",
			0.1,
			"soundImpactSoft6",
			0.1,
			"soundImpactSoft7",
			0.1
		};
		impactRubber[]=
		{
			"soundImpactSoft1",
			0.2,
			"soundImpactSoft2",
			0.2,
			"soundImpactSoft3",
			0.2,
			"soundImpactSoft4",
			0.1,
			"soundImpactSoft5",
			0.1,
			"soundImpactSoft6",
			0.1,
			"soundImpactSoft7",
			0.1
		};
		impactWater[]=
		{
			"soundImpactWater1",
			0.34999999,
			"soundImpactWater2",
			0.34999999,
			"soundImpactWater3",
			0.30000001
		};
		impactWood[]=
		{
			"soundImpactWoodExt1",
			0.25,
			"soundImpactWoodExt2",
			0.25,
			"soundImpactWoodExt3",
			0.25,
			"soundImpactWoodExt4",
			0.25
		};
		initTime=0;
		irLock=0;
		isCraterOriented=0;
		laserLock=0;
		lockSeekRadius=100;
		lockType=0;
		maneuvrability=1;
		manualControl=0;
		maverickweaponIndexOffset=0;
		maxControlRange=350;
		maxSpeed=0;
		mineBoundingDist=3;
		mineBoundingTime=3;
		mineDiveSpeed=1;
		mineFloating=-1;
		mineInconspicuousness=10;
		mineJumpEffects="";
		minePlaceDist=0.5;
		mineTrigger="RangeTrigger";
		minimumSafeZone=0.1;
		minTimeToLive=0;
		missileLockCone=0;
		model="\A3\Weapons_f\ammo\Handgrenade";
		multiSoundHit[]=
		{
			"soundHit1",
			0.2,
			"soundHit2",
			0.2,
			"soundHit3",
			0.2,
			"soundHit4",
			0.1,
			"soundHit5",
			0.15000001,
			"soundHit6",
			0.15000001
		};
		nvLock=0;
		proxyShape="";
		shadow=1;
		shootDistraction=0.15000001;
		sideAirFriction=1;
		simulation="shotGrenade";
		simulationStep=0.050000001;
		soundActivation[]={};
		soundDeactivation[]={};
		soundEngine[]=
		{
			"",
			1,
			1
		};
		soundFakeFall[]=
		{
			"soundFall",
			1
		};
		soundFall[]=
		{
			"",
			1,
			1
		};
		soundFly[]=
		{
			"",
			0.1,
			1,
			20
		};
		soundHit1[]=
		{
			"A3\Sounds_F\weapons\Explosion\gr_explosion_1",
			3.1622801,
			1,
			2000
		};
		soundHit2[]=
		{
			"A3\Sounds_F\weapons\Explosion\gr_explosion_2",
			3.1622801,
			1,
			2000
		};
		soundHit3[]=
		{
			"A3\Sounds_F\weapons\Explosion\gr_explosion_3",
			3.1622801,
			1,
			2000
		};
		soundHit4[]=
		{
			"A3\Sounds_F\weapons\Explosion\gr_explosion_4",
			3.1622801,
			1,
			2000
		};
		soundHit5[]=
		{
			"A3\Sounds_F\weapons\Explosion\gr_explosion_5",
			3.1622801,
			1,
			2000
		};
		soundHit6[]=
		{
			"A3\Sounds_F\weapons\Explosion\gr_explosion_6",
			3.1622801,
			1,
			2000
		};
		soundHit[]=
		{
			"",
			1,
			1
		};
		soundImpact[]=
		{
			"",
			1,
			1
		};
		soundImpactHard1[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_concrete_1",
			1.41254,
			1,
			65
		};
		soundImpactHard2[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_concrete_2",
			1.41254,
			1,
			65
		};
		soundImpactHard3[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_concrete_3",
			1.41254,
			1,
			65
		};
		soundImpactHard4[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_concrete_4",
			1.41254,
			1,
			65
		};
		soundImpactHard5[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_concrete_5",
			1.41254,
			1,
			65
		};
		soundImpactHard6[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_concrete_6",
			1.41254,
			1,
			65
		};
		soundImpactHard7[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_concrete_7",
			1.41254,
			1,
			65
		};
		soundImpactIron1[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_Metal_1",
			1.25893,
			1,
			95
		};
		soundImpactIron2[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_Metal_2",
			1.25893,
			1,
			95
		};
		soundImpactIron3[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_Metal_3",
			1.25893,
			1,
			95
		};
		soundImpactIron4[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_Metal_4",
			1.25893,
			1,
			95
		};
		soundImpactIron5[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_Metal_5",
			1.25893,
			1,
			95
		};
		soundImpactSoft1[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_grass_1",
			1.41254,
			1,
			45
		};
		soundImpactSoft2[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_grass_2",
			1.41254,
			1,
			45
		};
		soundImpactSoft3[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_grass_3",
			1.41254,
			1,
			45
		};
		soundImpactSoft4[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_grass_4",
			1.41254,
			1,
			45
		};
		soundImpactSoft5[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_grass_5",
			1.41254,
			1,
			45
		};
		soundImpactSoft6[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_grass_6",
			1.41254,
			1,
			45
		};
		soundImpactSoft7[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_grass_7",
			1.41254,
			1,
			45
		};
		soundImpactWater1[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_1",
			1.41254,
			1,
			55
		};
		soundImpactWater2[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_2",
			1.41254,
			1,
			55
		};
		soundImpactWater3[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_3",
			1.41254,
			1,
			55
		};
		soundImpactWoodExt1[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_wood_ext_1",
			1.41254,
			1,
			75
		};
		soundImpactWoodExt2[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_wood_ext_2",
			1.41254,
			1,
			75
		};
		soundImpactWoodExt3[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_wood_ext_3",
			1.41254,
			1,
			75
		};
		soundImpactWoodExt4[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_wood_ext_4",
			1.41254,
			1,
			75
		};
		soundTrigger[]={};
		submunitionAmmo="";
		supersonicCrackFar[]=
		{
			"",
			1,
			1
		};
		supersonicCrackNear[]=
		{
			"",
			1,
			1
		};
		suppressionRadiusHit=30;
		suppressionRadiusBulletClose=-1;
		typicalspeed=18;
		thrust=210;
		thrustTime=1.5;
		timeToLive=10;
		tracerColor[]={0.69999999,0.69999999,0.5,0.039999999};
		tracerColorR[]={0.69999999,0.69999999,0.5,0.039999999};
		trackLead=1;
		trackOversteer=1;
		underwaterHitRangeCoef="1.0f";
		visibleFire=0.5;
		visibleFireTime=1;
		indirectHit=25;
		indirectHitRange=8;
		waterEffectOffset=0.44999999;
		weaponLockSystem=0;
		whistleDist=28;
		whistleOnFire=0;
	};
	class mini_Grenade: GrenadeHand
	{
		deflecting=30;
		hit=6;
		indirectHit=20;
		indirectHitRange=4;
		model="\A3\Weapons_f\ammo\mini_frag";
		suppressionRadiusHit=12;
	};
	class G_40mm_HE: GrenadeHand
	{
		access=3;
		airFriction=-0.001;
		audibleFire=6;
		caliber=2;
		cost=10;
		deflecting=5;
		fuseDistance=15;
		explosionTime=0;
		hit=100;
		indirectHit=25;
		indirectHitRange=5;
		simulation="shotShell";
		supersonicCrackFar[]=
		{
			"A3\Sounds_F\weapons\Explosion\supersonic_crack_50meters",
			0.22387201,
			1,
			75
		};
		supersonicCrackNear[]=
		{
			"A3\Sounds_F\weapons\Explosion\supersonic_crack_close",
			0.316228,
			1,
			50
		};
		suppressionRadiusBulletClose=10;
		suppressionRadiusHit=30;
		thrust=210;
		thrustTime=1.5;
		timeToLive=20;
		typicalSpeed=185;
		underwaterHitRangeCoef="1.0f";
		visibleFire=6;
		visibleFireTime=3;
		whistleDist=16;
	};
};
class cfgMods
{
	author="Drahkken";
	timepacked="1663160045";
};
