#include "BIS_AddonInfo.hpp"
class CfgPatches
{
	class ADDON
	{
		name = SPOKE;
        author = AUTHOR;
        requiredVersion = REQUIRED_VERSION;
		addonRootClass="A3_Weapons_F_Mark";
		requiredAddons[]=
		{
			"A3_Weapons_F_Mark",
			"BFSQN_private_core"
		};
		units[]={};
		weapons[]=
		{
			"optic_AMS",
			"optic_KHS_old",
			"optic_DMS",
			"optic_LRPS",
			"optic_SOS"
		};
	};
};
class CfgWeapons
{
	class ItemCore;
	class InventoryItem_Base_F;
	class InventoryOpticsItem_Base_F;
	class optic_AMS_base: ItemCore
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_AMS_base";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		displayName="$STR_A3_cfgWeapons_optic_AMS_base0";
		model="\A3\Weapons_F_Mark\Acc\acco_ams_F.p3d";
		DLC="Mark";
		descriptionShort="$STR_A3_cfgWeapons_optic_AMS1";
		weaponInfoType="RscWeaponZeroing";
		overviewPicture="\A3\Data_F_Mark\Images\watermarkInfo_page17_ca.paa";
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=14;
			opticType=2;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F_Mark\Acc\reticle_acco_ams_F";
			class OpticsModes
			{
				class AMS
				{
					opticsID=1;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera2",
						"OpticsBlur3"
					};
					opticsZoomMin=0.025;
					opticsZoomMax=0.075000003;
					opticsZoomInit=0.075000003;
					discreteDistance[]={300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000};
					discreteDistanceInitIndex=2;
					distanceZoomMin=300;
					distanceZoomMax=2000;
					discretefov[]={0.075000003,0.025};
					discreteInitIndex=0;
					memoryPointCamera="opticView";
					modelOptics[]=
					{
						"\A3\Weapons_F_Mark\Acc\reticle_acco_ams_F",
						"\A3\Weapons_F_Mark\Acc\reticle_acco_ams_z_F"
					};
					visionMode[]={};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Iron
				{
					opticsID=2;
					opticsDisplayName="";
					useModelOptics=0;
					opticsPPEffects[]={};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					discretefov[]={};
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
					distanceZoomMin=200;
					distanceZoomMax=200;
					discreteInitIndex=0;
					cameraDir="";
				};
			};
		};
		inertia=0.2;
	};
	class optic_AMS: optic_AMS_base
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_AMS";
		scope=2;
		scopeCurator=1;
		scopeArsenal=2;
		displayName="$STR_A3_cfgWeapons_optic_AMS0";
		DLC="Mark";
		picture="\a3\Weapons_F_Mark\Data\UI\icon_optic_AMS_ca.paa";
	};
	class optic_KHS_base: ItemCore
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_KHS_base";
		scope=0;
		scopeCurator=0;
		scopeArsenal=0;
		displayName="$STR_A3_cfgWeapons_optic_KHS_base0";
		model="\A3\Weapons_F_Mark\Acc\acco_khs_blk_F.p3d";
		DLC="Mark";
		descriptionShort="$STR_A3_cfgWeapons_optic_KHS_blk1";
		weaponInfoType="RscWeaponZeroing";
		overviewPicture="\A3\Data_F_Mark\Images\watermarkInfo_page12_ca.paa";
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=14;
			opticType=2;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F_Mark\Acc\reticle_acco_khs_F";
			class OpticsModes
			{
				class KHS
				{
					opticsID=1;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera3",
						"OpticsBlur2"
					};
					opticsZoomMin=0.022700001;
					opticsZoomMax=0.053599998;
					opticsZoomInit=0.053599998;
					discreteDistance[]={300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000};
					discreteDistanceInitIndex=2;
					distanceZoomMin=300;
					distanceZoomMax=2000;
					discretefov[]={0.053599998,0.022700001};
					discreteInitIndex=0;
					memoryPointCamera="opticView";
					modelOptics[]=
					{
						"\A3\Weapons_F_Mark\Acc\reticle_acco_khs_F",
						"\A3\Weapons_F_Mark\Acc\reticle_acco_khs_z_F"
					};
					visionMode[]={};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Iron
				{
					opticsID=2;
					opticsDisplayName="";
					useModelOptics=0;
					opticsPPEffects[]={};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					discretefov[]={};
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
					distanceZoomMin=200;
					distanceZoomMax=200;
					discreteInitIndex=0;
					cameraDir="";
				};
			};
		};
		inertia=0.2;
	};
	class optic_KHS_blk: optic_KHS_base
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_KHS_blk";
		scope=2;
		scopeCurator=1;
		scopeArsenal=2;
		displayName="$STR_A3_cfgWeapons_optic_KHS_blk0";
		DLC="Mark";
		picture="\a3\Weapons_F_Mark\Data\UI\icon_optic_KHS_blk_ca.paa";
	};
	class optic_KHS_old: ItemCore
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_KHS_old";
		scope=2;
		scopeCurator=1;
		scopeArsenal=2;
		displayName="$STR_A3_cfgWeapons_optic_KHS_old0";
		picture="\a3\Weapons_F_Mark\Data\UI\icon_optic_KHS_old_ca.paa";
		model="\A3\Weapons_F_Mark\Acc\acco_khs_old_F.p3d";
		DLC="Mark";
		descriptionShort="$STR_A3_cfgWeapons_optic_KHS_blk1";
		weaponInfoType="RscWeaponZeroing";
		overviewPicture="\A3\Data_F_Mark\Images\watermarkInfo_page12_ca.paa";
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=14;
			opticType=2;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F_Mark\Acc\reticle_acco_khs_F";
			class OpticsModes
			{
				class KHS
				{
					opticsID=1;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera3",
						"OpticsBlur2"
					};
					opticsZoomMin=0.022700001;
					opticsZoomMax=0.053599998;
					opticsZoomInit=0.053599998;
					discreteDistance[]={300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000};
					discreteDistanceInitIndex=2;
					distanceZoomMin=300;
					distanceZoomMax=2000;
					discretefov[]={0.053599998,0.022700001};
					discreteInitIndex=0;
					memoryPointCamera="opticView";
					modelOptics[]=
					{
						"\A3\Weapons_F_Mark\Acc\reticle_acco_khs_F",
						"\A3\Weapons_F_Mark\Acc\reticle_acco_khs_z_F"
					};
					visionMode[]={};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Iron
				{
					opticsID=2;
					opticsDisplayName="";
					useModelOptics=0;
					opticsPPEffects[]={};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					discretefov[]={};
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
					distanceZoomMin=200;
					distanceZoomMax=200;
					discreteInitIndex=0;
					cameraDir="";
				};
			};
		};
		inertia=0.2;
	};
	class optic_SOS: ItemCore
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_SOS";
		scope=2;
		displayName="$STR_A3_cfgWeapons_optic_SOS0";
		picture="\a3\Weapons_F\acc\Data\UI\icon_optic_SOS_ca.paa";
		model="\A3\Weapons_F\acc\acco_Sniper_F";
		descriptionShort="$STR_A3_cfgWeapons_optic_SOS1";
		weaponInfoType="RscWeaponZeroing";
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=14;
			opticType=2;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_LRPS_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=1;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.050000001;
					opticsZoomMax=0.107;
					opticsZoomInit=0.107;
					discreteDistance[]={300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600};
					discreteDistanceInitIndex=0;
					distanceZoomMin=300;
					distanceZoomMax=1600;
					discretefov[]={0.107,0.050000001};
					discreteInitIndex=0;
					memoryPointCamera="opticView";
					modelOptics[]=
					{
						"\A3\Weapons_F\acc\reticle_sniper_F",
						"\A3\Weapons_F\acc\reticle_sniper_z_F"
					};
					visionMode[]={};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Iron
				{
					opticsID=2;
					opticsDisplayName="";
					useModelOptics=0;
					opticsPPEffects[]=
					{
						"",
						""
					};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					discretefov[]={};
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
					distanceZoomMin=200;
					distanceZoomMax=200;
					discreteInitIndex=0;
				};
			};
		};
		inertia=0.2;
	};
	class optic_DMS: ItemCore
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_DMS";
		scope=2;
		displayName="$STR_A3_CFGWEAPONS_ACC_DMS0";
		picture="\a3\Weapons_F\acc\Data\UI\icon_optic_DMS_ca.paa";
		model="\A3\Weapons_F_EPA\Acc\acco_marksman_F.p3d";
		descriptionShort="$STR_A3_CFGWEAPONS_ACC_DMS1";
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=12;
			opticType=2;
			optics=1;
			modelOptics="\A3\Weapons_f\acc\reticle_marksman_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=1;
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera2",
						"OpticsBlur3"
					};
					opticsZoomMin=0.0625;
					opticsZoomMax=0.125;
					opticsZoomInit=0.125;
					discreteDistance[]={100,200,300,400,500,600,700,800,900,1000,1100,1200};
					discreteDistanceInitIndex=1;
					distanceZoomMin=300;
					distanceZoomMax=1200;
					discretefov[]={0.125,0.0625};
					discreteInitIndex=0;
					memoryPointCamera="opticView";
					modelOptics[]=
					{
						"\A3\Weapons_F_EPA\acc\reticle_marksman_F",
						"\A3\Weapons_F_EPA\acc\reticle_marksman_z_F"
					};
					visionMode[]={};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Iron: Snip
				{
					opticsID=2;
					useModelOptics=0;
					opticsPPEffects[]=
					{
						"",
						""
					};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					discretefov[]={};
					distanceZoomMin=200;
					distanceZoomMax=200;
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
				};
			};
		};
		inertia=0.2;
	};
	class optic_LRPS: ItemCore
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="optic_LRPS";
		scope=2;
		displayName="$STR_A3_cfgWeapons_optic_LRPS0";
		picture="\A3\Weapons_F_EPB\Acc\Data\UI\gear_acco_sniper02_CA.paa";
		model="\A3\Weapons_F_EPB\Acc\acco_sniper02_F.p3d";
		descriptionShort="$STR_A3_cfgWeapons_optic_LRPS1";
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=16;
			opticType=2;
			weaponInfoType="RscWeaponRangeZeroingFOV";
			optics=1;
			modelOptics="\A3\Weapons_F\acc\reticle_sniper_F";
			class OpticsModes
			{
				class Snip
				{
					opticsID=1;
					opticsDisplayName="WFOV";
					useModelOptics=1;
					opticsPPEffects[]=
					{
						"OpticsCHAbera1",
						"OpticsBlur1"
					};
					opticsZoomMin=0.0099999998;
					opticsZoomMax=0.041999999;
					opticsZoomInit=0.041999999;
					discreteDistance[]={300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400};
					discreteDistanceInitIndex=2;
					distanceZoomMin=300;
					distanceZoomMax=2400;
					discretefov[]={0.041999999,0.0099999998};
					discreteInitIndex=0;
					memoryPointCamera="opticView";
					modelOptics[]=
					{
						"\A3\Weapons_F\acc\reticle_lrps_F",
						"\A3\Weapons_F\acc\reticle_lrps_z_F"
					};
					visionMode[]={};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					cameraDir="";
				};
				class Iron
				{
					opticsID=2;
					opticsDisplayName="";
					useModelOptics=0;
					opticsPPEffects[]={};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.25;
					opticsZoomMax=1.25;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					discretefov[]={};
					discreteDistance[]={200};
					discreteDistanceInitIndex=0;
					distanceZoomMin=200;
					distanceZoomMax=200;
					discreteInitIndex=0;
					cameraDir="";
				};
			};
		};
		inertia=0.2;
	};
};